<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'username' => '900000000',
                'nama' => 'Async Await',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Jl. Margoasri Gang 11',
                'kelurahan' => 'Puro',
                'kecamatan' => 'Karangmalang',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 1,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000001',
                'nama' => 'Farhan Wahyudi',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Sungkul Rt. 5 Rw. 2',
                'kelurahan' => 'Plumbungan',
                'kecamatan' => 'Karangmalang',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 2,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000002',
                'nama' => 'Adi Muallimin',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Jl. Buntu No. 5',
                'kelurahan' => 'Ngadirejo',
                'kecamatan' => 'Kerjo',
                'kabupaten' => 'Karanganyar',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000003',
                'nama' => 'Erwan Sulistyo',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Jl. Menik No. 9',
                'kelurahan' => 'Baliharjo',
                'kecamatan' => 'Tanon',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 3,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000004',
                'nama' => 'Kurnia Wulandari',
                'gender' => 'P',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Perum Achidatama',
                'kelurahan' => 'Jetis',
                'kecamatan' => 'Kebakkramat',
                'kabupaten' => 'Karanganyar',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000005',
                'nama' => 'Masrudin',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Newung Rt. 7 Rw. 6',
                'kelurahan' => 'Mentikan',
                'kecamatan' => 'Gorang Gareng',
                'kabupaten' => 'Ngawi',
                'provinsi' => 'Jawa Timur',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '900000006',
                'nama' => 'Dewi',
                'gender' => 'P',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Newung Rt. 7 Rw. 6',
                'kelurahan' => 'Mentikan',
                'kecamatan' => 'Gorang Gareng',
                'kabupaten' => 'Ngawi',
                'provinsi' => 'Jawa Timur',
                'hp' => "090207927",
                'gelar' => 'S.Pd.',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 4,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '121001',
                'nama' => 'Boolean Alinea Pertama',
                'gender' => 'P',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Mantup Rt. 3 Rw. 4',
                'kelurahan' => 'Bendo',
                'kecamatan' => 'Sukodono',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => '',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 17,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '121002',
                'nama' => 'Array Alinea Kedua',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Ngundaan Gang 7',
                'kelurahan' => 'Gersapi',
                'kecamatan' => 'Gondang',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => '',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 17,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '121003',
                'nama' => 'Banyu',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Mantup Rt. 3 Rw. 4',
                'kelurahan' => 'Bendo',
                'kecamatan' => 'Sukodono',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => '',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 17,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],
            [
                'username' => '121004',
                'nama' => 'Liwa',
                'gender' => 'L',
                'ttl' => 'Sragen, 12 April 2000',
                'alamat' => 'Ngundaan Gang 7',
                'kelurahan' => 'Gersapi',
                'kecamatan' => 'Gondang',
                'kabupaten' => 'Sragen',
                'provinsi' => 'Jawa Tengah',
                'hp' => "090207927",
                'gelar' => '',
                'sub' => "SD",
                'ket' => 'Aktif',
                'catatan' => 'Baik',
                'profile' => 'profile.jpg',
                'ktp' => 'ktp.jpg',
                'kk' => 'kk.jpg',
                'berkas' => 'berkas.jpg',
                'password' => password_hash(123456, PASSWORD_DEFAULT),
                'role_id' => 17,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s")
            ],

        ];

        // Simple Queries
        // $this->db->query('INSERT INTO role (role, created_at, updated_at) VALUES(:role:, :created_at:, :updated_at:)', $data);

        // Using Query Builder
        // $this->db->table('role')->insert($data);
        $this->db->table('user')->insertBatch($data);
    }
}
